### ISSUE TITLE
onRemove parameter on selectedBlockRenderer is actually onChange

### ISSUE THREAD

**Issue by rogeriocsilva** [maslianok/react-select-me#33]
In the README docs it is specified that the `selectedBlockRenderer` receives as an argument the `onRemove` function. I was passing alongside my close icon and nothing happened. After a while I had to see the source code and noticed that the function that actually is passed along is the `onChange`, instead of the `onRemoveSelected`

https://github.com/maslianok/react-select-me#L196

**Comment by maslianok** [comment]
Yes, everything is correct.

I think you misunderstand the purpose of that callback. Let me explain:

`selectedBlockRenderer` is the function that renders the whole block with selected items.  
It receives 4 arguments:  
- `selectedOptions` the options to be rendered. These are the selected options. You must render them inside `selectedBlockRenderer` function
- `onRemove` is the function that must be triggered on a certain option when you want to remove it. For example, you receive [1,2,3,4] as the `selectedOptions`, so you have to call `onRemove(1)` in order to deselect option 1
- `selectedValueRenderer` is the default value renderer. The library uses this function in order to render every single selected option. Something like `selectedOptions.map(option => selectedValueRenderer(option))`. You can use it or skip and implement your own value renderer. It's up yo you.
- `searchInputRenderer` is the default function to render search input. The same as above: use it or implement you own logic

I hope it become more clear. Let me know if you have any questions...

**Comment by rogeriocsilva** [comment]
Yes, I did understood the purpose of the callback. But in order to work I had to do following, since in the source code, you're passing along the onChange function instead of the onRemove function (I know the original post is about selectedBlockRenderer, but this functions is passed along with the same issue  ): 
<img width="522" alt="image" src="https://user-images.githubusercontent.com/10121694/111879834-0402d800-89a0-11eb-9740-5d68983adb39.png">

**Comment by maslianok** [comment]
And `onChange` function removes the value when it's selected

**Comment by rogeriocsilva** [comment]
Yes, if you send the second argument as true, right? I didn't mean to say this was wrong in any way, but if you only read the docs the onRemove function will not remove the selected option. I'll try to add a sandbox tomorrow.

**Comment by maslianok** [comment]
onChange toggles the value

You can also pass a second parameter to force-remove value (nothing happens in case it's not selected)

**Comment by maslianok** [comment]
In our case, when the value is selected, onChange toggles its state (removes it from the list of selected values)

we don't have to pass any additional parameters in this case
